import tkinter as tk
from tkinter import *


root = tk.Tk()
root.geometry("800x800")
root.title("Button Console")


def command():
    pass


btn1 = tk.Button(root, text="btn1", command=command)
btn1.grid(column=0, row=1)
btn2 = tk.Button(root, text="btn2", command=command)
btn2.grid(column=0, row=2)
btn3 = tk.Button(root, text="btn3", command=command)
btn3.grid(column=0, row=3)
btn4 = tk.Button(root, text="button 4", command=command)
btn4.grid(column=0, row=4)
btn5 = tk.Button(root, text="button 5", command=command)
btn5.grid(column=0, row=5)
btn6 = tk.Button(root, text="button 6", command=command)
btn6.grid(column=0, row=6)
btn7 = tk.Button(root, text="button 7", command=command)
btn7.grid(column=0, row=7)
btn8 = tk.Button(root, text="button 8", command=command)
btn8.grid(column=0, row=8)
btn9 = tk.Button(root, text="button 9", command=command)
btn9.grid(column=0, row=9)
btn10 = tk.Button(root, text="button 10", command=command)
btn10.grid(column=0, row=10)


btn11 = tk.Button(root, text="btn11", command=command)
btn11.grid(column=1, row=1)
btn12 = tk.Button(root, text="btn12", command=command)
btn12.grid(column=1, row=2)
btn13 = tk.Button(root, text="auto2", command=command)
btn13.grid(column=1, row=3)
btn14 = tk.Button(root, text="button 4", command=command)
btn14.grid(column=1, row=4)
btn15 = tk.Button(root, text="button 5", command=command)
btn15.grid(column=1, row=5)
btn16 = tk.Button(root, text="button 6", command=command)
btn16.grid(column=1, row=6)
btn17 = tk.Button(root, text="button 7", command=command)
btn17.grid(column=1, row=7)
btn18 = tk.Button(root, text="button 8", command=command)
btn18.grid(column=1, row=8)
btn19 = tk.Button(root, text="button 9", command=command)
btn19.grid(column=1, row=9)
btn20 = tk.Button(root, text="button 10", command=command)
btn20.grid(column=1, row=10)


btn21 = tk.Button(root, text="btn21", command=command)
btn21.grid(column=2, row=1)
btn22 = tk.Button(root, text="btn22", command=command)
btn22.grid(column=2, row=2)
btn23 = tk.Button(root, text="auto2", command=command)
btn23.grid(column=2, row=3)
btn24 = tk.Button(root, text="button 4", command=command)
btn24.grid(column=2, row=4)
btn25 = tk.Button(root, text="button 5", command=command)
btn25.grid(column=2, row=5)
btn26 = tk.Button(root, text="button 6", command=command)
btn26.grid(column=2, row=6)
btn27 = tk.Button(root, text="button 7", command=command)
btn27.grid(column=2, row=7)
btn28 = tk.Button(root, text="button 8", command=command)
btn28.grid(column=2, row=8)
btn29 = tk.Button(root, text="button 9", command=command)
btn29.grid(column=2, row=9)
btn30 = tk.Button(root, text="button 10", command=command)
btn30.grid(column=2, row=10)

btn31 = tk.Button(root, text="-----", command=command)
btn31.grid(column=3, row=1)
btn32 = tk.Button(root, text="------", command=command)
btn32.grid(column=3, row=2)
btn33 = tk.Button(root, text="------", command=command)
btn33.grid(column=3, row=3)
btn34 = tk.Button(root, text="button 34", command=command)
btn34.grid(column=3, row=4)
btn35 = tk.Button(root, text="button 35", command=command)
btn35.grid(column=3, row=5)
btn36 = tk.Button(root, text="button 36", command=command)
btn36.grid(column=3, row=6)
btn37 = tk.Button(root, text="button 37", command=command)
btn37.grid(column=3, row=7)
btn38 = tk.Button(root, text="button 38", command=command)
btn38.grid(column=3, row=8)
btn39 = tk.Button(root, text="39", command=command)
btn39.grid(column=3, row=9)
btn40 = tk.Button(root, text="button 40", command=command)
btn40.grid(column=3, row=10)


btn41 = tk.Button(root, text="btn41", command=command)
btn41.grid(column=4, row=1)
btn42 = tk.Button(root, text="btn42", command=command)
btn42.grid(column=4, row=2)
btn43 = tk.Button(root, text="btn43", command=command)
btn43.grid(column=4, row=3)
btn44 = tk.Button(root, text="button 44", command=command)
btn44.grid(column=4, row=4)
btn45 = tk.Button(root, text="button 45", command=command)
btn45.grid(column=4, row=5)
btn46 = tk.Button(root, text="button 46", command=command)
btn46.grid(column=4, row=6)
btn47 = tk.Button(root, text="button 47", command=command)
btn47.grid(column=4, row=7)
btn48 = tk.Button(root, text="button 48", command=command)
btn48.grid(column=4, row=8)
btn49 = tk.Button(root, text="button 49", command=command)
btn49.grid(column=4, row=9)
btn50 = tk.Button(root, text="button 50", command=command)
btn50.grid(column=4, row=10)


root.mainloop()
