import tkinter as tk
from tkinter import *


root = tk.Tk()
root.geometry("800x800")
root.title("Button Console")


def command():
    pass


btn1 = tk.Button(root, text="btn1", command=command)
btn1.grid(column=0, row=1)
btn2 = tk.Button(root, text="btn2", command=command)
btn2.grid(column=0, row=2)
btn3 = tk.Button(root, text="btn3", command=command)
btn3.grid(column=0, row=3)
btn4 = tk.Button(root, text="button 4", command=command)
btn4.grid(column=0, row=4)
btn5 = tk.Button(root, text="button 5", command=command)
btn5.grid(column=0, row=5)
btn6 = tk.Button(root, text="button 6", command=command)
btn6.grid(column=0, row=6)
btn7 = tk.Button(root, text="button 7", command=command)
btn7.grid(column=0, row=7)
btn8 = tk.Button(root, text="button 8", command=command)
btn8.grid(column=0, row=8)
btn9 = tk.Button(root, text="button 9", command=command)
btn9.grid(column=0, row=9)
btn10 = tk.Button(root, text="button 10", command=command)
btn10.grid(column=0, row=10)


btn11 = tk.Button(root, text="btn11", command=command)
btn11.grid(column=1, row=1)
btn12 = tk.Button(root, text="btn12", command=command)
btn12.grid(column=1, row=2)
btn13 = tk.Button(root, text="auto2", command=command)
btn13.grid(column=1, row=3)
btn14 = tk.Button(root, text="button 4", command=command)
btn14.grid(column=1, row=4)
btn15 = tk.Button(root, text="button 5", command=command)
btn15.grid(column=1, row=5)
btn16 = tk.Button(root, text="button 6", command=command)
btn16.grid(column=1, row=6)
btn17 = tk.Button(root, text="button 7", command=command)
btn17.grid(column=1, row=7)
btn18 = tk.Button(root, text="button 8", command=command)
btn18.grid(column=1, row=8)
btn19 = tk.Button(root, text="button 9", command=command)
btn19.grid(column=1, row=9)
btn20 = tk.Button(root, text="button 10", command=command)
btn20.grid(column=1, row=10)


btn21 = tk.Button(root, text="btn21", command=command)
btn21.grid(column=2, row=1)
btn22 = tk.Button(root, text="btn22", command=command)
btn22.grid(column=2, row=2)
btn23 = tk.Button(root, text="auto2", command=command)
btn23.grid(column=2, row=3)
btn24 = tk.Button(root, text="button 4", command=command)
btn24.grid(column=2, row=4)
btn25 = tk.Button(root, text="button 5", command=command)
btn25.grid(column=2, row=5)
btn26 = tk.Button(root, text="button 6", command=command)
btn26.grid(column=2, row=6)
btn27 = tk.Button(root, text="button 7", command=command)
btn27.grid(column=2, row=7)
btn28 = tk.Button(root, text="button 8", command=command)
btn28.grid(column=2, row=8)
btn29 = tk.Button(root, text="button 9", command=command)
btn29.grid(column=2, row=9)
btn30 = tk.Button(root, text="button 10", command=command)
btn30.grid(column=2, row=10)

btn31 = tk.Button(root, text="-----", command=command)
btn31.grid(column=3, row=1)
btn32 = tk.Button(root, text="------", command=command)
btn32.grid(column=3, row=2)
btn33 = tk.Button(root, text="------", command=command)
btn33.grid(column=3, row=3)
btn34 = tk.Button(root, text="button 34", command=command)
btn34.grid(column=3, row=4)
btn35 = tk.Button(root, text="button 35", command=command)
btn35.grid(column=3, row=5)
btn36 = tk.Button(root, text="button 36", command=command)
btn36.grid(column=3, row=6)
btn37 = tk.Button(root, text="button 37", command=command)
btn37.grid(column=3, row=7)
btn38 = tk.Button(root, text="button 38", command=command)
btn38.grid(column=3, row=8)
btn39 = tk.Button(root, text="39", command=command)
btn39.grid(column=3, row=9)
btn40 = tk.Button(root, text="button 40", command=command)
btn40.grid(column=3, row=10)


btn41 = tk.Button(root, text="btn41", command=command)
btn41.grid(column=4, row=1)
btn42 = tk.Button(root, text="btn42", command=command)
btn42.grid(column=4, row=2)
btn43 = tk.Button(root, text="btn43", command=command)
btn43.grid(column=4, row=3)
btn44 = tk.Button(root, text="button 44", command=command)
btn44.grid(column=4, row=4)
btn45 = tk.Button(root, text="button 45", command=command)
btn45.grid(column=4, row=5)
btn46 = tk.Button(root, text="button 46", command=command)
btn46.grid(column=4, row=6)
btn47 = tk.Button(root, text="button 47", command=command)
btn47.grid(column=4, row=7)
btn48 = tk.Button(root, text="button 48", command=command)
btn48.grid(column=4, row=8)
btn49 = tk.Button(root, text="button 49", command=command)
btn49.grid(column=4, row=9)
btn50 = tk.Button(root, text="button 50", command=command)
btn50.grid(column=4, row=10)


btbtn31 = tk.Button(root, text="-----", command=command)
btbtn31.grid(column=11, row=1)
btbtn32 = tk.Button(root, text="------", command=command)
btbtn32.grid(column=11, row=2)
btbtn33 = tk.Button(root, text="------", command=command)
btbtn33.grid(column=11, row=3)
btbtn34 = tk.Button(root, text="button 34", command=command)
btbtn34.grid(column=11, row=4)
btbtn35 = tk.Button(root, text="button 35", command=command)
btbtn35.grid(column=11, row=5)
btbtn36 = tk.Button(root, text="button 36", command=command)
btbtn36.grid(column=11, row=6)
btbtn37 = tk.Button(root, text="button 37", command=command)
btbtn37.grid(column=11, row=7)
btbtn38 = tk.Button(root, text="button 38", command=command)
btbtn38.grid(column=11, row=8)
btbtn39 = tk.Button(root, text="39", command=command)
btbtn39.grid(column=11, row=9)
btbtn40 = tk.Button(root, text="button 40", command=command)
btbtn40.grid(column=11, row=10)


bbtn1 = tk.Button(root, text="bbtn1", command=command)
bbtn1.grid(column=5, row=1)
bbtn2 = tk.Button(root, text="bbtn2", command=command)
bbtn2.grid(column=5, row=2)
bbtn3 = tk.Button(root, text="bbtn3", command=command)
bbtn3.grid(column=5, row=3)
bbtn4 = tk.Button(root, text="button 4", command=command)
bbtn4.grid(column=5, row=4)
bbtn5 = tk.Button(root, text="button 5", command=command)
bbtn5.grid(column=5, row=5)
bbtn6 = tk.Button(root, text="button 6", command=command)
bbtn6.grid(column=5, row=16)
bbtn7 = tk.Button(root, text="button 7", command=command)
bbtn7.grid(column=5, row=17)
bbtn8 = tk.Button(root, text="button 8", command=command)
bbtn8.grid(column=5, row=18)
bbtn9 = tk.Button(root, text="button 9", command=command)
bbtn9.grid(column=5, row=19)
bbtn10 = tk.Button(root, text="button 10", command=command)
bbtn10.grid(column=5, row=20)

bb1 = tk.Button(root, text="bb1", command=command)
bb1.grid(column=6, row=1)
bb2 = tk.Button(root, text="bb2", command=command)
bb2.grid(column=6, row=2)
bb3 = tk.Button(root, text="bb3", command=command)
bb3.grid(column=6, row=3)
bb4 = tk.Button(root, text="button 4", command=command)
bb4.grid(column=6, row=4)
bb5 = tk.Button(root, text="button 5", command=command)
bb5.grid(column=6, row=5)
bb6 = tk.Button(root, text="button 6", command=command)
bb6.grid(column=6, row=16)
bb7 = tk.Button(root, text="button 7", command=command)
bb7.grid(column=6, row=17)
bb8 = tk.Button(root, text="button 8", command=command)
bb8.grid(column=6, row=18)
bb9 = tk.Button(root, text="button 9", command=command)
bb9.grid(column=6, row=19)
bb10 = tk.Button(root, text="button 10", command=command)
bb10.grid(column=6, row=20)
bb11 = tk.Button(root, text="bb11", command=command)
bb11.grid(column=7, row=1)
bb12 = tk.Button(root, text="bb12", command=command)
bb12.grid(column=7, row=2)
bb13 = tk.Button(root, text="auto2", command=command)
bb13.grid(column=7, row=3)
bb14 = tk.Button(root, text="button 4", command=command)
bb14.grid(column=7, row=4)
bb15 = tk.Button(root, text="button 5", command=command)
bb15.grid(column=7, row=5)
bb16 = tk.Button(root, text="button 6", command=command)
bb16.grid(column=7, row=16)
bb17 = tk.Button(root, text="button 7", command=command)
bb17.grid(column=7, row=17)
bb18 = tk.Button(root, text="button 8", command=command)
bb18.grid(column=7, row=18)
bb19 = tk.Button(root, text="button 9", command=command)
bb19.grid(column=7, row=19)
bb20 = tk.Button(root, text="button 10", command=command)
bb20.grid(column=7, row=20)
btbtn1 = tk.Button(root, text="btbtn1", command=command)
btbtn1.grid(column=8, row=1)
btbtn2 = tk.Button(root, text="btbtn2", command=command)
btbtn2.grid(column=8, row=2)
btbtn3 = tk.Button(root, text="btbtn3", command=command)
btbtn3.grid(column=8, row=3)
btbtn4 = tk.Button(root, text="button 4", command=command)
btbtn4.grid(column=8, row=4)
btbtn5 = tk.Button(root, text="button 5", command=command)
btbtn5.grid(column=8, row=5)
btbtn6 = tk.Button(root, text="button 6", command=command)
btbtn6.grid(column=8, row=6)
btbtn7 = tk.Button(root, text="button 7", command=command)
btbtn7.grid(column=8, row=7)
btbtn8 = tk.Button(root, text="button 8", command=command)
btbtn8.grid(column=8, row=8)
btbtn9 = tk.Button(root, text="button 9", command=command)
btbtn9.grid(column=8, row=9)
btbtn10 = tk.Button(root, text="button 10", command=command)
btbtn10.grid(column=8, row=10)
btbtn11 = tk.Button(root, text="btbtn11", command=command)
btbtn11.grid(column=9, row=1)
btbtn12 = tk.Button(root, text="btbtn12", command=command)
btbtn12.grid(column=9, row=2)
btbtn13 = tk.Button(root, text="auto2", command=command)
btbtn13.grid(column=9, row=3)
btbtn14 = tk.Button(root, text="button 4", command=command)
btbtn14.grid(column=9, row=4)
btbtn15 = tk.Button(root, text="button 5", command=command)
btbtn15.grid(column=9, row=5)
btbtn16 = tk.Button(root, text="button 6", command=command)
btbtn16.grid(column=9, row=6)
btbtn17 = tk.Button(root, text="button 7", command=command)
btbtn17.grid(column=9, row=7)
btbtn18 = tk.Button(root, text="button 8", command=command)
btbtn18.grid(column=9, row=8)
btbtn19 = tk.Button(root, text="button 9", command=command)
btbtn19.grid(column=9, row=9)
btbtn20 = tk.Button(root, text="button 10", command=command)
btbtn20.grid(column=9, row=10)
btbtn21 = tk.Button(root, text="btbtn21", command=command)
btbtn21.grid(column=10, row=1)
btbtn22 = tk.Button(root, text="btbtn22", command=command)
btbtn22.grid(column=10, row=2)
btbtn23 = tk.Button(root, text="auto2", command=command)
btbtn23.grid(column=10, row=3)
btbtn24 = tk.Button(root, text="button 4", command=command)
btbtn24.grid(column=10, row=4)
btbtn25 = tk.Button(root, text="button 5", command=command)
btbtn25.grid(column=10, row=5)
btbtn26 = tk.Button(root, text="button 6", command=command)
btbtn26.grid(column=10, row=6)
btbtn27 = tk.Button(root, text="button 7", command=command)
btbtn27.grid(column=10, row=7)
btbtn28 = tk.Button(root, text="button 8", command=command)
btbtn28.grid(column=10, row=8)
btbtn29 = tk.Button(root, text="button 9", command=command)
btbtn29.grid(column=10, row=9)
btbtn30 = tk.Button(root, text="button 10", command=command)
btbtn30.grid(column=10, row=10)

btbtn41 = tk.Button(root, text="btbtn41", command=command)
btbtn41.grid(column=12, row=1)
btbtn42 = tk.Button(root, text="btbtn42", command=command)
btbtn42.grid(column=12, row=1)
btbtn43 = tk.Button(root, text="btbtn43", command=command)
btbtn43.grid(column=12, row=3)
btbtn44 = tk.Button(root, text="button 44", command=command)
btbtn44.grid(column=12, row=4)
btbtn45 = tk.Button(root, text="button 45", command=command)
btbtn45.grid(column=12, row=5)
btbtn46 = tk.Button(root, text="button 46", command=command)
btbtn46.grid(column=12, row=6)
btbtn47 = tk.Button(root, text="button 47", command=command)
btbtn47.grid(column=12, row=7)
btbtn48 = tk.Button(root, text="button 48", command=command)
btbtn48.grid(column=12, row=8)
btbtn49 = tk.Button(root, text="button 49", command=command)
btbtn49.grid(column=12, row=9)
btbtn50 = tk.Button(root, text="button 50", command=command)
btbtn50.grid(column=12, row=10)


root.mainloop()
