btn1 = tk.Button(top, text="Tab11", command=lambda: openfile(1))
btn1.grid(column=0, row=1)
btn2 = tk.Button(top, text="Tab2", command=lambda: openfile(2))
btn2.grid(column=0, row=2)
btn3 = tk.Button(top, text="Tab3", command=lambda: openfile(3))
btn3.grid(column=0, row=3)
btn4 = tk.Button(top, text="Tab4", command=lambda: openfile(4))
btn4.grid(column=0, row=4)
btn5 = tk.Button(top, text="Tab5", command=lambda: openfile(5))
btn5.grid(column=0, row=5)
btn6 = tk.Button(top, text="Tab 6", command=lambda: openfile(6))
btn6.grid(column=0, row=6)
btn7 = tk.Button(top, text="Tab 7", command=lambda: openfile(7))
btn7.grid(column=0, row=7)
btn8 = tk.Button(top, text="Tab 8", command=lambda: openfile(8))
btn8.grid(column=0, row=8)
btn9 = tk.Button(top, text="Tab 9", command=lambda: openfile(9))
btn9.grid(column=0, row=9)
btn10 = tk.Button(top, text="Tab 10", command=lambda: openfile(10))
btn10.grid(column=0, row=10)


btn11 = tk.Button(top, text="Save1", command=command)
btn11.grid(column=1, row=1)
btn12 = tk.Button(top, text="Save2", command=command)
btn12.grid(column=1, row=2)
btn13 = tk.Button(top, text="Save3", command=command)
btn13.grid(column=1, row=3)
btn14 = tk.Button(top, text="Save4", command=command)
btn14.grid(column=1, row=4)
btn15 = tk.Button(top, text="Save 5", command=command)
btn15.grid(column=1, row=5)
btn16 = tk.Button(top, text="Save6", command=command)
btn16.grid(column=1, row=6)
btn17 = tk.Button(top, text="Save7", command=command)
btn17.grid(column=1, row=7)
btn18 = tk.Button(top, text="Save8", command=command)
btn18.grid(column=1, row=8)
btn19 = tk.Button(top, text="Save9", command=command)
btn19.grid(column=1, row=9)
btn20 = tk.Button(top, text="Save10", command=command)
btn20.grid(column=1, row=10)
